### ISSUE TITLE
Question about the required attribute

### ISSUE THREAD

**Issue by dubonzi** [desislavsd/vue-select#11]
I'm trying to set the `required` attribute on the select but when I do so the option list isn't displayed until  I type something in the search field. The behaviour I want is the default `required` behaviour so the browser warns the user. 

`<vSelect required />` works as expected but it doesn't work if I use a prop to set the attribute i.e `<vSelect :required="required" />` (omitted other props for brevity)

**Comment by desislavsd** [comment]
Hm.. The syntax should make no difference in the behavior. I'll check. 

Anyway, you **should not use** `required` attribute for validating `<v-select />` as part of your form validation. **The value of the input (the query) and the selected value ( the model value) are two very different things.** Normally the component will **clear the input** as soon as it looses focus in order to display the selected value. Therefore if you set the `required` attribute the form will be invalid despite that a value has been selected, because instead of validating the model you are validating the query.

As stated in the beginning of the [props page](https://desislavsd.gitbook.io/vue-select/props) in the docs these attributes can be utilized for altering the behavior of the component:

> The vSelect component does not inherit attributes and all additional attributes are directly passed to the internal input element and can be used for further altering the behavior of the component like: `disabled`, `readonly`, `pattern`, `required`, `autofocus`. **The fetching function won't be called unless the input is** `:valid`

For example:

- **required** - will make the component load the options only after a query is present
- **readonly** - will make the component work as classic select element as you won't be able to type
- etc...

Therefore you can not rely on the `required` attribute for validating your model. The component is agnostic about the validation system you use. Using [vuelidate](https://vuelidate.js.org) for example will be straightforward.

**Comment by dubonzi** [comment]
Awesome, thanks for the detailed answer! At first I didn't understand that the underlying input was only used for the query, that was my mistake. I'll try to integrate vuelidate into my custom component.
