### ISSUE TITLE
Duplicate keys detected

### ISSUE THREAD

**Issue by ecwio** [desislavsd/vue-select#9]
I am sorry but I cannot figure this out; moreover I am not sure why the end user should have to take care of this ? Isn't it possible to generate unique keys on the component side ?

I have a simple year generated list like so :

`[ {label:'2000', value:2000 }, {label:'2001', value:2001 },etc...]`

and I get the duplicate key error. I use the component like this:

```
<v-select v-model="creationYear" :from="createYearsList" :as="'label::value'" :closeOnSelect="true" :clearOnSelect="true" :clearOnClose="false" :tagging="false">
         <template v-slot:both="{ option }">
                 {{option.label}}
          </template>
</v-select>
```

For the life of me I cannot find the answer in your doc. Obvioulsy I must be doing something wrong because a unique key issue cannot happen ?

Can you please clarify (hopefully with the doc) with some clear example on how to deal with that ?

also why is the problem sometime going away if I do `:as="'label:label:label'"` ?? I have no idea... What is the difference between `::` and `:` ? 

it seems that using `::` return to me the full object (this is what I want) but `:` only returns the value in my v-model

where do I take care of these keys ?

Please help me understand.

edit:
I see in your code that you use `:key="option.index"` so that is going to create duplicates all the time right ? why don't you use `:key="option.index+someUniqueIdentifier"` ?

**Comment by desislavsd** [comment]
@signmeuptwice I am sorry you are having hard time with the documentation. Definitely going to improve the corresponding sections. 

So the problem here is related to the `as` property. It takes place when you are working with non primitive options as with the `[ {label:'2000', value:2000 }, {label:'2001', value:2001 },etc...]` in your example. The `as` property is expected to be an array of exactly 3 strings (paths): `[ label, value, index ]`. Where:
-  __label__ is the path to the property of your option object i.e `{label:'2000', value:2000}` which should be used as a display value and also in filtering. It also is the property to which the query will be set when creating new option in tagging mode.
- __value__ path is to the property that should be set as model value when an option is selected; if the path is an empty string, the whole object will be assigned to the model. 
- __index__ path is very important. It should point to a unique primitive value for each option and is applied as `:key` in the internal `v-for` of the options list. It is also __used when comparing two options objects__ e.g. for detecting if an option is selected or not. Therefore it cannot be some random generated value and is important for the end user to have control over it. Usually you would pass a path that points to the option's id.

Some possible values would be: `:as="['label', 'value', 'id']"`, `:as="['label', '', 'id']"`. 

As this is quite verbose it is supported to pass these paths as a simple `: ` separated string:  `as="label:value:id"` and `as="label::id"` respectively.

That said, for your particular example the  `:as="'label::value'"` is correct and should be working just fine.  But if you get `duplicate key` error it means you have two or more options with the same `value` which in fact should be something you did not intend and in which case the plugin actually helped you spot an error in your data ;)

**Comment by ecwio** [comment]
@desislavsd thank you for the detailed explanation; you were right I had a duplicate in my data but I am still glad I asked because now It is a lot clearer to me. 
I did not realise that `::` was just and empty second value and therefore providing an index.
You should definitely copy/paste this answer in your doc :)
And thank you for the great work, this component is really good; does it all in a very nice way; neat !
